### ISSUE TITLE
下面报错是怎么回事，求指教

### ISSUE THREAD

**Issue by Icakacm** [KeJunMao/edgegpt#9]
file:///root/.npm/_npx/752531cac679291a/node_modules/c12/dist/index.mjs:12
  const targetEnvironment = options.env ?? process.env;
                                                                  ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)

**Comment by KeJunMao** [comment]
try node 16.x
